Fix error in from_replies_flows
kytos-ng/flow_stats pull request #34
Opened 2022-09-13 02:56 UTC by gretelliz

Fix #21 

This is a new PR to deal with the kytos/of_core.flow_stats.received event for OF 0x04, 
Function 'handle_stats_received' has been added, that looks for 'replies_flows' in the event content, iterates through it, and sets the generic flows.
Function 'from_replies_flows' has also been added, which maps Flow from v0x04 into GenericFlow.

Testing locally, I have used a linear net of 3 switches. I could see into the controller in kytos for the switch '00:00:00:00:00:00:00:01':

{'dpid': '00:00:00:00:00:00:00:01',
 'connection': Connection('127.0.0.1', 44186, <asyncio.TransportSocket fd=111, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 6653), raddr=('127.0.0.1', 44186)>, Switch('00:00:00:00:00:00:00:01'), <ConnectionState.ESTABLISHED: 2>),
 'features': FeaturesReply(xid=UBInt32(361952766)),
 'firstseen': datetime.datetime(2022, 9, 13, 2, 40, 47, 377716, tzinfo=datetime.timezone.utc),
 'lastseen': datetime.datetime(2022, 9, 13, 2, 47, 50, 57016, tzinfo=datetime.timezone.utc),
 'sent_xid': None,
 'waiting_for_reply': False,
 'request_timestamp': 0,
 'mac2port': {},
 'flood_table': {},
 'interfaces': {4294967294: Interface('s1', 4294967294, Switch('00:00:00:00:00:00:00:01')),
  1: Interface('s1-eth1', 1, Switch('00:00:00:00:00:00:00:01')),
  2: Interface('s1-eth2', 2, Switch('00:00:00:00:00:00:00:01'))},
 'flows': [<napps.kytos.of_core.v0x04.flow.Flow at 0x7fd1a42e7190>,
  <napps.kytos.of_core.v0x04.flow.Flow at 0x7fd1a42f4550>,
  <napps.kytos.of_core.v0x04.flow.Flow at 0x7fd1a42f4370>],
 'description': {'manufacturer': 'Nicira, Inc.',
  'hardware': 'Open vSwitch',
  'software': '2.9.8',
  'serial': 'None',
  'data_path': 'None'},
 '_id': '00:00:00:00:00:00:00:01',
 '_interface_lock': <unlocked _thread.lock object at 0x7fd230022300>,
 'metadata': {},
 '_active': True,
 '_enabled': True,
 'generic_flows': [<napps.amlight.flow_stats.main.GenericFlow at 0x7fd1a45e7df0>,
  <napps.amlight.flow_stats.main.GenericFlow at 0x7fd234ed4220>,
  <napps.amlight.flow_stats.main.GenericFlow at 0x7fd1a42dd8b0>],
 'generic_new_flows': [<napps.amlight.flow_stats.main.GenericFlow at 0x7fd1a45e7df0>,
  <napps.amlight.flow_stats.main.GenericFlow at 0x7fd234ed4220>,
  <napps.amlight.flow_stats.main.GenericFlow at 0x7fd1a42dd8b0>]}

 Moreover, I saw the traces with sdntrace_cp:

{
    "result": [
        {
            "dpid": "00:00:00:00:00:00:00:01",
            "port": 1,
            "time": "2022-09-12 21:09:55.023383",
            "type": "starting",
            "vlan": 100
        },
        {
            "dpid": "00:00:00:00:00:00:00:02",
            "port": 2,
            "time": "2022-09-12 21:09:55.023432",
            "type": "trace",
            "vlan": 3366
        },
        {
            "dpid": "00:00:00:00:00:00:00:03",
            "port": 2,
            "time": "2022-09-12 21:09:55.023464",
            "type": "trace",
            "vlan": 2344
        }
    ]
}

However, I wonder if these traces correspond to event 'kytos/of_core.v0x04.messages.in.ofpt_multipart_reply'

2022-09-13 14:01 UTC, viniarck requested changes
> However, I wonder if these traces correspond to event 'kytos/of_core.v0x04.messages.in.ofpt_multipart_reply'

@gretelliz, yes, you're supposed to remove `kytos/of_core.v0x04.messages.in.ofpt_multipart_reply` since you're replacing it with `'kytos/of_core.flow_stats.received'`, otherwise you'd have this conflict that you've mentioned. Remove it and make sure to test it locally again and make sure to update the changelog.rst file summarizing the change. Other than that, the change looks good me, congrats. 

You could also copy `flow04.cookie` when mapping a new `GenericFlow` but since we'll nuke `GenericFlow` in a next opportunity no need to do it.

2022-09-13 15:34 UTC, gretelliz commented
@viniarck That's it. I removed 'kytos/of_core.v0x04.messages.in.ofpt_multipart_reply' and verified locally that sdntrace_cp does not return valid traces. Only the special trace with type 'start' is returned.

2022-09-13 16:57 UTC, gretelliz commented
Yes, I have added it again until I make a decision. I can make a new commit by removing kytos/of_core.v0x04.messages.in.ofpt_multipart_reply? You can check what I say about the traces.

2022-09-13 17:20 UTC, viniarck commented
> Hi @viniarck. Yes, I have added it again until I make a decision. I can make a new commit by removing kytos/of_core.v0x04.messages.in.ofpt_multipart_reply? You can check what I say about the traces.

@gretelliz, I think there's a misunderstanding here of what needs to be accomplished, the purpose of issue #21 is to replace `kytos/of_core.v0x04.messages.in.ofpt_multipart_reply` with `kytos/of_core.flow_stats.received`. As it is, you've got concurrent writes in place, yes, please, remove it.

2022-09-14 19:03 UTC, viniarck commented
@gretelliz the last commit looks great. However, it seems that the actions being copied from flow04 has an issue, could you double check and fix this? Once it's ready for review again let me know, thanks.

```
kytos $> [flow.to_dict() for flow in controller.switches[sw1].generic_flows]
Out[3]:
[{'version': '0x04',
  'dl_src': 'ee:ee:ee:ee:ee:02',
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 50000,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'vlan_vid': 3799,
  'dl_type': 35020,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 1000,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'in_port': 1,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 100,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'in_port': 2,
  'vlan_vid': 3739,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 100,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []}]
```

```
kytos $> [flow.as_dict() for flow in controller.switches[sw1].flows]
Out[2]:
[{'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_src': 'ee:ee:ee:ee:ee:02'},
  'priority': 50000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': 'ae4413b4aa528250ff74cadec530cb8b',
  'stats': {'byte_count': 0,
   'duration_sec': 2,
   'duration_nsec': 974000000,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_vlan': 3799, 'dl_type': 35020},
  'priority': 1000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12321848580485677057,
  'id': '5cd66b3ec5c0437b3d163f18e8491250',
  'stats': {'byte_count': 7014,
   'duration_sec': 2,
   'duration_nsec': 965000000,
   'packet_count': 167},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 1},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12317901981778834756,
  'id': '52dd988b6e1bf3a59a0c689f194d251d',
  'stats': {'byte_count': 420,
   'duration_sec': 418,
   'duration_nsec': 173000000,
   'packet_count': 6},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'push_vlan', 'tag_type': 's'},
     {'vlan_id': 3739, 'action_type': 'set_vlan'},
     {'port': 2, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 2, 'dl_vlan': 3739},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12317901981778834756,
  'id': '6f91bb4585077e88eacf549dfd723ec9',
  'stats': {'byte_count': 518,
   'duration_sec': 418,
   'duration_nsec': 169000000,
   'packet_count': 7},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'pop_vlan'},
     {'port': 1, 'action_type': 'output'}]}]}]

kytos $>

```

2022-09-14 19:04 UTC, viniarck commented
@gretelliz the last commit looks great. However, it seems that the actions being copied from flow04 has an issue, could you double check and fix this? Once it's ready for review again let me know, thanks.

```
kytos $> [flow.to_dict() for flow in controller.switches[sw1].generic_flows]
Out[3]:
[{'version': '0x04',
  'dl_src': 'ee:ee:ee:ee:ee:02',
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 50000,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'vlan_vid': 3799,
  'dl_type': 35020,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 1000,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'in_port': 1,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 100,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []},
 {'version': '0x04',
  'in_port': 2,
  'vlan_vid': 3739,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 100,
  'table_id': 0,
  'cookie': None,
  'buffer_id': None,
  'actions': []}]
```

```
kytos $> [flow.as_dict() for flow in controller.switches[sw1].flows]
Out[2]:
[{'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_src': 'ee:ee:ee:ee:ee:02'},
  'priority': 50000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 0,
  'id': 'ae4413b4aa528250ff74cadec530cb8b',
  'stats': {'byte_count': 0,
   'duration_sec': 2,
   'duration_nsec': 974000000,
   'packet_count': 0},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_vlan': 3799, 'dl_type': 35020},
  'priority': 1000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12321848580485677057,
  'id': '5cd66b3ec5c0437b3d163f18e8491250',
  'stats': {'byte_count': 7014,
   'duration_sec': 2,
   'duration_nsec': 965000000,
   'packet_count': 167},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 1},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12317901981778834756,
  'id': '52dd988b6e1bf3a59a0c689f194d251d',
  'stats': {'byte_count': 420,
   'duration_sec': 418,
   'duration_nsec': 173000000,
   'packet_count': 6},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'push_vlan', 'tag_type': 's'},
     {'vlan_id': 3739, 'action_type': 'set_vlan'},
     {'port': 2, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 2, 'dl_vlan': 3739},
  'priority': 100,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12317901981778834756,
  'id': '6f91bb4585077e88eacf549dfd723ec9',
  'stats': {'byte_count': 518,
   'duration_sec': 418,
   'duration_nsec': 169000000,
   'packet_count': 7},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'pop_vlan'},
     {'port': 1, 'action_type': 'output'}]}]}]

kytos $>

```

2022-09-15 14:19 UTC, gretelliz commented
Hi @viniarck, I did a new commit.

2022-09-15 16:43 UTC, viniarck commented
> Hi @viniarck, I did a new commit.

@gretelliz I've just reviewed it, looks good to me. The only thing remaining is updating the changelog, after confirming that locally it's running as expected, you've probably run it again but it's good to put the info here otherwise the reviewer doesn't know.

2022-09-15 17:23 UTC, gretelliz commented
@viniarck Done.

You're right. Here is the output with the correct data inside the action field:

kytos $> [flow.as_dict() for flow in controller.switches['00:00:00:00:00:00:00:01'].flows]
Out[2]:
[{'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 1},
  'priority': 32768,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12310228866111668291,
  'id': '2ccf86f01e20bda59bb99d7475c1441e',
  'stats': {'byte_count': 210,
   'duration_sec': 231,
   'duration_nsec': 698000000,
   'packet_count': 3},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'push_vlan', 'tag_type': 's'},
     {'vlan_id': 2046, 'action_type': 'set_vlan'},
     {'port': 2, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'in_port': 2, 'dl_vlan': 2046},
  'priority': 32768,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12310228866111668291,
  'id': '53256391e1134e3148e81be425e46864',
  'stats': {'byte_count': 148,
   'duration_sec': 231,
   'duration_nsec': 684000000,
   'packet_count': 2},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'action_type': 'pop_vlan'},
     {'port': 1, 'action_type': 'output'}]}]},
 {'switch': '00:00:00:00:00:00:00:01',
  'table_id': 0,
  'match': {'dl_vlan': 3799, 'dl_type': 35020},
  'priority': 1000,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'cookie': 12321848580485677057,
  'id': '5cd66b3ec5c0437b3d163f18e8491250',
  'stats': {'byte_count': 3234,
   'duration_sec': 234,
   'duration_nsec': 895000000,
   'packet_count': 77},
  'cookie_mask': 0,
  'instructions': [{'instruction_type': 'apply_actions',
    'actions': [{'port': 4294967293, 'action_type': 'output'}]}]}]

kytos $> [flow.to_dict() for flow in controller.switches['00:00:00:00:00:00:00:01'].generic_flows]
Out[2]:
[{'version': '0x04',
  'in_port': 1,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 32768,
  'table_id': 0,
  'cookie': 12310228866111668291,
  'buffer_id': None,
  'actions': [{'action_type': 'push_vlan', 'tag_type': 's'},
   {'vlan_id': 2046, 'action_type': 'set_vlan'},
   {'port': 2, 'action_type': 'output'}]},
 {'version': '0x04',
  'in_port': 2,
  'vlan_vid': 2046,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 32768,
  'table_id': 0,
  'cookie': 12310228866111668291,
  'buffer_id': None,
  'actions': [{'action_type': 'pop_vlan'},
   {'port': 1, 'action_type': 'output'}]},
 {'version': '0x04',
  'vlan_vid': 3799,
  'dl_type': 35020,
  'idle_timeout': 0,
  'hard_timeout': 0,
  'priority': 1000,
  'table_id': 0,
  'cookie': 12321848580485677057,
  'buffer_id': None,
  'actions': [{'port': 4294967293, 'action_type': 'output'}]}]

2022-09-15 18:15 UTC, viniarck approved these changes
Looks good to me, congrats landing this, @gretelliz.

2022-09-15 18:15 UTC, merged